name: Build
on:
  - pull_request
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: '16'

      - name: Install, Build and Test 🔧
        run: |
          yarn
          yarn build